# Generated by Django 5.1.3 on 2024-12-03 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('nombre_conductor', models.CharField(max_length=100)),
                ('fecha_carga', models.DateField()),
                ('guia', models.CharField(max_length=100)),
                ('patente', models.CharField(max_length=20)),
                ('estacion_servicio', models.CharField(max_length=100)),
                ('suministro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kms', models.IntegerField()),
                ('consumo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(upload_to='imagenes_guias/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
